services:
  postgres:
    image: postgres:18
    container_name: go-test-postgres
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
