BEGIN;

ALTER TABLE users
ALTER COLUMN created_at
TYPE BIGINT
USING EXTRACT(EPOCH FROM created_at)::BIGINT;

ALTER TABLE libraries
ALTER COLUMN created_at
TYPE BIGINT
USING EXTRACT(EPOCH FROM created_at)::BIGINT;

ALTER TABLE tracks
ALTER COLUMN uploaded_at
TYPE BIGINT
USING EXTRACT(EPOCH FROM uploaded_at)::BIGINT;

COMMIT;