ALTER TABLE libraries DROP COLUMN IF EXISTS total_tracks;
ALTER TABLE tracks DROP COLUMN IF EXISTS duration;
ALTER TABLE tracks DROP COLUMN IF EXISTS file_path;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS description VARCHAR(255);