BEGIN;

ALTER TABLE users
ALTER COLUMN created_at
TYPE TIMESTAMPTZ
USING TO_TIMESTAMP(created_at);

ALTER TABLE libraries
ALTER COLUMN created_at
TYPE TIMESTAMPTZ
USING TO_TIMESTAMP(created_at);

ALTER TABLE tracks
ALTER COLUMN uploaded_at
TYPE TIMESTAMPTZ
USING TO_TIMESTAMP(uploaded_at);

COMMIT;
