ALTER TABLE libraries ADD COLUMN total_tracks INTEGER NOT NULL;
ALTER TABLE tracks ADD COLUMN duration INTEGER NOT NULL;
ALTER TABLE tracks ADD COLUMN file_path VARCHAR(255) NOT NULL;
ALTER TABLE tracks DROP COLUMN IF EXISTS description;