ALTER TABLE libraries ADD COLUMN IF NOT EXISTS total_tracks INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS duration INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS file_path VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE tracks DROP COLUMN IF EXISTS description;